api_version = "2025-10"

[[extensions]]
name = "velora-discount"
handle = "velora-discount"

uid = "5d6e0510-ed0e-11c7-97f2-4867c874a8ee795f0836"
type = "function"
description = "Velora bundle discounts"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/run.graphql"
  export = "run"
